// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SCHEMA_SCHEMA_H_
#define FLATBUFFERS_GENERATED_SCHEMA_SCHEMA_H_

#include "flatbuffers/flatbuffers.h"

namespace schema {

struct Person;
struct PersonBuilder;

struct Group;
struct GroupBuilder;

struct Client;
struct ClientBuilder;

struct ClientList;
struct ClientListBuilder;

enum ClientType {
  ClientType_Person = 0,
  ClientType_Group = 1,
  ClientType_MIN = ClientType_Person,
  ClientType_MAX = ClientType_Group
};

inline const ClientType (&EnumValuesClientType())[2] {
  static const ClientType values[] = {
    ClientType_Person,
    ClientType_Group
  };
  return values;
}

inline const char * const *EnumNamesClientType() {
  static const char * const names[3] = {
    "Person",
    "Group",
    nullptr
  };
  return names;
}

inline const char *EnumNameClientType(ClientType e) {
  if (flatbuffers::IsOutRange(e, ClientType_Person, ClientType_Group)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesClientType()[index];
}

struct Person FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef PersonBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_AGE = 6,
    VT_WEIGHT = 8,
    VT_GENDER = 10
  };
  const flatbuffers::String *name() const {
    return GetPointer<const flatbuffers::String *>(VT_NAME);
  }
  int32_t age() const {
    return GetField<int32_t>(VT_AGE, 0);
  }
  float weight() const {
    return GetField<float>(VT_WEIGHT, 0.0f);
  }
  const flatbuffers::String *gender() const {
    return GetPointer<const flatbuffers::String *>(VT_GENDER);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<int32_t>(verifier, VT_AGE,0) &&
           VerifyField<float>(verifier, VT_WEIGHT,0.0f) &&
           VerifyOffset(verifier, VT_GENDER) &&
           verifier.VerifyString(gender()) &&
           verifier.EndTable();
  }
};

struct PersonBuilder {
  typedef Person Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_name(flatbuffers::Offset<flatbuffers::String> name) {
    fbb_.AddOffset(Person::VT_NAME, name);
  }
  void add_age(int32_t age) {
    fbb_.AddElement<int32_t>(Person::VT_AGE, age, 0);
  }
  void add_weight(float weight) {
    fbb_.AddElement<float>(Person::VT_WEIGHT, weight, 0.0f);
  }
  void add_gender(flatbuffers::Offset<flatbuffers::String> gender) {
    fbb_.AddOffset(Person::VT_GENDER, gender);
  }
  explicit PersonBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Person> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Person>(end);
    return o;
  }
};

inline flatbuffers::Offset<Person> CreatePerson(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> name = 0,
    int32_t age = 0,
    float weight = 0.0f,
    flatbuffers::Offset<flatbuffers::String> gender = 0) {
  PersonBuilder builder_(_fbb);
  builder_.add_gender(gender);
  builder_.add_weight(weight);
  builder_.add_age(age);
  builder_.add_name(name);
  return builder_.Finish();
}

inline flatbuffers::Offset<Person> CreatePersonDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    int32_t age = 0,
    float weight = 0.0f,
    const char *gender = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto gender__ = gender ? _fbb.CreateString(gender) : 0;
  return schema::CreatePerson(
      _fbb,
      name__,
      age,
      weight,
      gender__);
}

struct Group FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef GroupBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_GROUPNAME = 4,
    VT_AVERAGEAGE = 6,
    VT_AVERAGEWEIGHT = 8,
    VT_NAMES = 10
  };
  const flatbuffers::String *groupName() const {
    return GetPointer<const flatbuffers::String *>(VT_GROUPNAME);
  }
  int32_t averageAge() const {
    return GetField<int32_t>(VT_AVERAGEAGE, 0);
  }
  float averageWeight() const {
    return GetField<float>(VT_AVERAGEWEIGHT, 0.0f);
  }
  const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *names() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *>(VT_NAMES);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_GROUPNAME) &&
           verifier.VerifyString(groupName()) &&
           VerifyField<int32_t>(verifier, VT_AVERAGEAGE,0) &&
           VerifyField<float>(verifier, VT_AVERAGEWEIGHT,0.0f) &&
           VerifyOffset(verifier, VT_NAMES) &&
           verifier.VerifyVector(names()) &&
           verifier.VerifyVectorOfStrings(names()) &&
           verifier.EndTable();
  }
};

struct GroupBuilder {
  typedef Group Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_groupName(flatbuffers::Offset<flatbuffers::String> groupName) {
    fbb_.AddOffset(Group::VT_GROUPNAME, groupName);
  }
  void add_averageAge(int32_t averageAge) {
    fbb_.AddElement<int32_t>(Group::VT_AVERAGEAGE, averageAge, 0);
  }
  void add_averageWeight(float averageWeight) {
    fbb_.AddElement<float>(Group::VT_AVERAGEWEIGHT, averageWeight, 0.0f);
  }
  void add_names(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> names) {
    fbb_.AddOffset(Group::VT_NAMES, names);
  }
  explicit GroupBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Group> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Group>(end);
    return o;
  }
};

inline flatbuffers::Offset<Group> CreateGroup(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> groupName = 0,
    int32_t averageAge = 0,
    float averageWeight = 0.0f,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> names = 0) {
  GroupBuilder builder_(_fbb);
  builder_.add_names(names);
  builder_.add_averageWeight(averageWeight);
  builder_.add_averageAge(averageAge);
  builder_.add_groupName(groupName);
  return builder_.Finish();
}

inline flatbuffers::Offset<Group> CreateGroupDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *groupName = nullptr,
    int32_t averageAge = 0,
    float averageWeight = 0.0f,
    const std::vector<flatbuffers::Offset<flatbuffers::String>> *names = nullptr) {
  auto groupName__ = groupName ? _fbb.CreateString(groupName) : 0;
  auto names__ = names ? _fbb.CreateVector<flatbuffers::Offset<flatbuffers::String>>(*names) : 0;
  return schema::CreateGroup(
      _fbb,
      groupName__,
      averageAge,
      averageWeight,
      names__);
}

struct Client FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef ClientBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TYPE = 4,
    VT_CLIENT = 6,
    VT_PERSON = 8,
    VT_GROUP = 10
  };
  schema::ClientType type() const {
    return static_cast<schema::ClientType>(GetField<int8_t>(VT_TYPE, 0));
  }
  schema::ClientType client() const {
    return static_cast<schema::ClientType>(GetField<int8_t>(VT_CLIENT, 0));
  }
  const schema::Person *person() const {
    return GetPointer<const schema::Person *>(VT_PERSON);
  }
  const schema::Group *group() const {
    return GetPointer<const schema::Group *>(VT_GROUP);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_TYPE,0) &&
           VerifyField<int8_t>(verifier, VT_CLIENT,0) &&
           VerifyOffset(verifier, VT_PERSON) &&
           verifier.VerifyTable(person()) &&
           VerifyOffset(verifier, VT_GROUP) &&
           verifier.VerifyTable(group()) &&
           verifier.EndTable();
  }
};

struct ClientBuilder {
  typedef Client Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_type(schema::ClientType type) {
    fbb_.AddElement<int8_t>(Client::VT_TYPE, static_cast<int8_t>(type), 0);
  }
  void add_client(schema::ClientType client) {
    fbb_.AddElement<int8_t>(Client::VT_CLIENT, static_cast<int8_t>(client), 0);
  }
  void add_person(flatbuffers::Offset<schema::Person> person) {
    fbb_.AddOffset(Client::VT_PERSON, person);
  }
  void add_group(flatbuffers::Offset<schema::Group> group) {
    fbb_.AddOffset(Client::VT_GROUP, group);
  }
  explicit ClientBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Client> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Client>(end);
    return o;
  }
};

inline flatbuffers::Offset<Client> CreateClient(
    flatbuffers::FlatBufferBuilder &_fbb,
    schema::ClientType type = schema::ClientType_Person,
    schema::ClientType client = schema::ClientType_Person,
    flatbuffers::Offset<schema::Person> person = 0,
    flatbuffers::Offset<schema::Group> group = 0) {
  ClientBuilder builder_(_fbb);
  builder_.add_group(group);
  builder_.add_person(person);
  builder_.add_client(client);
  builder_.add_type(type);
  return builder_.Finish();
}

struct ClientList FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef ClientListBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CLIENTS = 4
  };
  const flatbuffers::Vector<flatbuffers::Offset<schema::Client>> *clients() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<schema::Client>> *>(VT_CLIENTS);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_CLIENTS) &&
           verifier.VerifyVector(clients()) &&
           verifier.VerifyVectorOfTables(clients()) &&
           verifier.EndTable();
  }
};

struct ClientListBuilder {
  typedef ClientList Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_clients(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<schema::Client>>> clients) {
    fbb_.AddOffset(ClientList::VT_CLIENTS, clients);
  }
  explicit ClientListBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<ClientList> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<ClientList>(end);
    return o;
  }
};

inline flatbuffers::Offset<ClientList> CreateClientList(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<schema::Client>>> clients = 0) {
  ClientListBuilder builder_(_fbb);
  builder_.add_clients(clients);
  return builder_.Finish();
}

inline flatbuffers::Offset<ClientList> CreateClientListDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<flatbuffers::Offset<schema::Client>> *clients = nullptr) {
  auto clients__ = clients ? _fbb.CreateVector<flatbuffers::Offset<schema::Client>>(*clients) : 0;
  return schema::CreateClientList(
      _fbb,
      clients__);
}

inline const schema::ClientList *GetClientList(const void *buf) {
  return flatbuffers::GetRoot<schema::ClientList>(buf);
}

inline const schema::ClientList *GetSizePrefixedClientList(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<schema::ClientList>(buf);
}

inline bool VerifyClientListBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<schema::ClientList>(nullptr);
}

inline bool VerifySizePrefixedClientListBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<schema::ClientList>(nullptr);
}

inline void FinishClientListBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<schema::ClientList> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedClientListBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<schema::ClientList> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace schema

#endif  // FLATBUFFERS_GENERATED_SCHEMA_SCHEMA_H_
